export const HISTORY = "HISTORY";
export const WISHLIST = "WISHLIST";
export const REMOVE_FROM_HISTORY = "REMOVE_FROM_HISTORY";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const ADD_BLOG = "ADD_BLOG";
export const PRODUCT_LOADED = "PRODUCT_LOADED";
export const TOGGLE_TAGS = "TOGGLE_TAGS";
export const REMOVE_BLOG = "REMOVE_BLOG";
